name: Build Anniw

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: build anniw
              run: |
                  yarn install
                  yarn build
              env:
                  CI: true
            - name: upload dist
              uses: actions/upload-artifact@v2
              with:
                  name: anniw-dist
                  path: dist/